volumes:
  foodgram_data:
  static_data:
  media_volume:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - foodgram_db
    volumes:
      - static_data:/backend_static
      - media_volume:/app/media

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_data:/frontend_static

  gateway:
    build: ./nginx/
    volumes:
      - static_data:/staticfiles/
      - media_volume:/app/media
    ports:
      - 8000:80
    depends_on:
    - backend
    - frontend