# Generated by Django 4.2.22 on 2025-10-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
